### ISSUE TITLE
Is R 3.6.3 a strict requirement?

### ISSUE THREAD

**Issue by jjv5** [bioinfoDZ/RISC#1]
Is the requirement for R 3.6.3 needed? Will not install in R 4.0.2.  Is it known not to work in R 4?

**Comment by bioinfoDZ** [comment]
RISC is developed in R v3.6.3 and can be run in all the versions of R v4. We already tested that. Thanks.

**Comment by jjv5** [comment]
We find this not to be the case:

Warning message:
package ‘RISC’ is not available (for R version 4.0.2)
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

**Comment by jjv5** [comment]
Pardon me - disregard. I wasn’t grabbing from git.
